name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

main = "src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "t.870113.xyz"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.t.870113.xyz", custom_domain = true },
  { pattern = "quay.t.870113.xyz", custom_domain = true },
  { pattern = "gcr.t.870113.xyz", custom_domain = true },
  { pattern = "k8s-gcr.t.870113.xyz", custom_domain = true },
  { pattern = "k8s.t.870113.xyz", custom_domain = true },
  { pattern = "ghcr.t.870113.xyz", custom_domain = true },
  { pattern = "cloudsmith.t.870113.xyz", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
